[CORE-12562] Support React 18
goodhood-eu/i18n-polyglot pull request #9
Opened 2023-04-17 19:38 UTC by spossner

[JIRA Story](https://jira.nebenan.de/browse/CORE-12562)

Upgrade to React 18, drop mocha because no tests in the package (or keep for consistency?) and upgraded to storybook 7

2023-04-18 14:23 UTC, eliasbraun requested changes

2023-04-18 14:23 UTC, eliasbraun commented on src/components/stories/Component.jsx
> +export const Component = () => (
Component might be a too generic name... 
Why did you switch from  T?

2023-04-18 14:23 UTC, eliasbraun commented on package.json
> -    "typescript": "^4.1.2"
I wonder why that was in there before 🤔

2023-04-18 14:23 UTC, eliasbraun commented on src/components/stories/Component.stories.js
> +// More on how to set up stories at: https://storybook.js.org/docs/react/writing-stories/introduction
I guess we can get rid of that comment

2023-04-18 14:23 UTC, eliasbraun commented on src/components/stories/Component.stories.js
> +};
Was that WIP?

2023-04-18 14:23 UTC, eliasbraun commented on src/components/stories/InternationalHook.stories.js
> +};
🤔

2023-04-18 14:23 UTC, eliasbraun commented on src/components/stories/LocaleHook.stories.js
> +// More on how to set up stories at: https://storybook.js.org/docs/react/writing-stories/introduction
Same like above

2023-04-18 14:23 UTC, eliasbraun commented on src/components/stories/LocaleHook.stories.js
> +// More on writing stories with args: https://storybook.js.org/docs/react/writing-stories/args
Same

2023-04-18 14:23 UTC, eliasbraun commented on src/components/stories/THook.stories.js
> +// More on how to set up stories at: https://storybook.js.org/docs/react/writing-stories/introduction
same

2023-04-18 14:23 UTC, eliasbraun commented on src/components/stories/THook.stories.js
> +};
same

2023-04-20 14:00 UTC, peterhass approved these changes
nice stories!

2023-04-20 14:01 UTC, eliasbraun approved these changes

2023-04-20 14:08 UTC, merged